name: CasoArt
favicon: null
layout_spectrum: 0.41776092420332134
typography_spectrum: 0.8143270015716553
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.10901372809894383
  lightness: 0.1446642098017037
  saturation: 0.2805212587118149
  rhythmicContrast: 0.938045192277059
purpose: []
